export const AUTHENTICATED_USER = "AUTHENTICATED_USER"
export const CLEAN_ALERT = "CLEAN_ALERT"
export const SHOW_ALERT = "SHOW_ALERT"
export const HIDE_ALERT = "SHOW_ALERT"

export const SUCCESSFUL_SIGNUP = "SUCCESSFUL_SIGNUP"
export const UNSUCCESSFUL_SIGNUP = "UNSUCCESSFUL_SIGNUP"

export const SUCCESSFUL_LOGIN = "SUCCESSFUL_LOGIN"
export const UNSUCCESSFUL_LOGIN = "UNSUCCESSFUL_LOGIN"

export const LOGOUT = "LOGOUT"

export const UPLOAD_FILE= "UPLOAD_FILE"
export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS"
export const UPLOAD_FILE_UNSUCCESS = "UPLOAD_FILE_UNSUCCESS"

export const CREATE_URL_SUCCESS = "CREATE_URL_SUCCESS"
export const CREATE_URL_UNSUCCESS = "CREATE_URL_UNSUCCESS"

export const CLEAN_STATE = "CLEAN_STATE"

export const ADD_PASSWORD = "ADD_PASSWORD"
export const ADD_DOWNLOADS = "ADD_DOWNLOADS"
